const actiontypes = Object.freeze({
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  USER_LOGOUT: "USER_LOGOUT",

  FETCH_OPTION_ARTIST_SUCCESS: "FETCH_OPTION_ARTIST_SUCCESS",
  FETCH_OPTION_ARTIST_FAIL: "FETCH_OPTION_ARTIST_FAIL",

  // GET_ALL_SONG_SUCCESS: "GET_ALL_SONG_SUCCESS",
  // GET_ALL_SONG_FAIL: "GET_ALL_SONG_FAIL",
});
export default actiontypes;
